### ISSUE TITLE
Enhance text in `createUiDefinition` to aid people getting an entitlement.

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#40]
The current text in the `createUiDefinition.json` regarding entitlement says:

> Provide an entitled IBMid to provision the WebSphere cluster. [Learn more](https://www.ibm.com/ibmid/myibm/help/us/helpdesk.html).

This issue requests that we enhance the text:
* To make it very clear that the deployment will fail if the IBMid is not entitled.
* Give the user some guidance on how to go about getting an entitlement.

**Comment by gcharters** [comment]
I don't think there's an ideal solution, but this is the best I have at the moment:

>This offer is Bring-Your-Own-License. You will be required to enter your registered IBM ID prior to successfully deploying this offer and your IBM ID must have active WebSphere entitlements associated with it. If you find that provisioning fails due to lack of entitlements, please contact the primary or secondary contacts for your IBM Passport Advantage Site who should be able to grant you access or follow steps at IBM eCustomer Care for further assistance. This offer also assume you are properly licensed to run offers in Microsoft Azure.

**Comment by edburns** [comment]
Please assign this to @majguo

**Comment by git4rk** [comment]
Here is the text suggested by IDD team (Pam):
This offer is Bring-Your-Own-License. To deploy this offer, you must enter your registered IBM ID and your IBM ID must have active WebSphere entitlements associated with it. If provisioning fails due to lack of entitlements, ask the primary or secondary contacts for your IBM Passport Advantage site to grant you access or follow steps at [IBM eCustomer Care](https://www-112.ibm.com/software/howtobuy/passportadvantage/homepage/ecarec) for further assistance. This offer also assumes you are properly licensed to run offers in Microsoft Azure.

**Comment by majguo** [comment]
Thanks @git4rk . The updated text has been applied to PR #83.
